- name: Print clipboard string
  debug:
    msg: "vless://{{ xray_uuid.stdout }}@{{ domain }}:{{ xray_port }}?type=grpc&serviceName=api.v1.telemetry.EventStream&mode=gun&security=reality&pbk={{ x25519_pbk.stdout }}&fp=firefox&sni={{ domain }}&sid={{ short_id.stdout }}&encryption=none#%F0%9F%87%A9%F0%9F%87%AA%20{{ domain }}"
- name: XRay outbound config
  debug:
    msg: |
          {
            "tag": "default",
            "protocol": "vless",
            "settings": {
              "vnext": [
                {
                  "address": "{{ domain }}",
                  "port": {{ xray_port }},
                  "users": [
                    {
                      "id": "{{ xray_uuid.stdout }}",
                      "encryption": "none"
                    }
                  ]
                }
              ]
            },
            "streamSettings": {
              "network": "grpc",
              "security": "reality",
              "grpcSettings": {
                "serviceName": "api.v1.telemetry.EventStream",
                "multiMode": false
              },
              "realitySettings": {
                "serverName": "{{ domain }}",
                "fingerprint": "firefox",
                "publicKey": "{{ x25519_pbk.stdout }}",
                "shortId": "{{ short_id.stdout }}",
                "spiderX": ""
              }
            }
          }
- name: Sing-box outbound config
  debug:
    msg: |
          {
              "type": "vless",
              "server": "{{ domain }}",
              "server_port": {{ xray_port }},
              "uuid": "{{ xray_uuid.stdout }}",
              "tls": {
                  "enabled": true,
                  "insecure": false,
                  "server_name": "{{ domain }}",
                  "utls": {
                      "enabled": true,
                      "fingerprint": "firefox"
                  },
                  "reality": {
                      "enabled": true,
                      "public_key": "{{ x25519_pbk.stdout }}",
                      "short_id": "{{ short_id.stdout }}"
                  }
              },
              "transport": {
                  "type": "grpc",
                  "service_name": "api.v1.telemetry.EventStream"
              }
          }
- name: Print PBK, SID and UUID to connect to server.
  debug:
    msg: "UUID: {{ xray_uuid.stdout }}, SID: {{ short_id.stdout }}, PBK: {{ x25519_pbk.stdout }}"
